### ISSUE TITLE
Can't noclip thru blocks on a server even when enabled

### ISSUE THREAD

**Issue by HerrCraziDev** [hashalite/Freecam#111]
Aloha 

Running Freecam on Fabric here. I have disabled collisions in the mod's settings, but can't apparently noclip thru blocks on a server. It works fine on my own server, but not on a friend's server. 
I expected to be able to fly thru blocks regardless of the server, as this is a client mod and does not sends movement packets to the server.

**Comment by hashalite** [comment]
Hey, the modrinth version disables noclip in muliplayer if you are not an operator. Are you using the modrinth version?

**Comment by HerrCraziDev** [comment]
Yeah. I switched to the Curseforge version and it works. Thanks !
Is that a Modrinth requirement? Sounds peculiar.

**Comment by hashalite** [comment]
No problem! It is indeed a Modrinth requirement.

**Comment by DraconicNEO** [comment]
> No problem! It is indeed a Modrinth requirement.

Modrinth sound like absolute pricks, too bad they're the only ones with better site functionality than curseforge (really hope we get some better mod sites than them soon).

**Comment by DraconicNEO** [comment]
> > Modrinth sound like absolute pricks, too bad they're the only ones with better site functionality than curseforge (really hope we get some better mod sites than them soon).
> 
> Yeah. They're pickier than Curseforge, but at least they're open-source, easy to navigate, and have standards. Curseforge is bloated, feels like the average internet service nowadays trying to squeeze out as much as possible from the users (ads, personal data, paid advantages, own "desktop" tools). Well Curseforge is far from the worst, and it's been generally a good platform in my eyes. I still like them, and they've improved the website these years. But Modrinth feels more minimal, lighter, simpler, which only makes me the merrier. Keep it simple stupid.

I do think that modrinth as a technical platform is superior, however I do not think it is beneficial to the community to cater to gatekeeping server admins who claim anything they dislike is ""cheating"". I'm going to call it gatekeeping because it goes against that open nature of Minecraft to do that, at least in my opinion, maybe some people disagree (see if I care). If people want to police their own servers, they can do that, but trying to gatekeep the community and servers other than their own which may or may not even care is honestly too far in my book. 

At least Modrinth is open source though so one could set up an instance of it without their weird gatekeeping requirements and then people could get all those benefits without the drawbacks.
