### ISSUE TITLE
About the Japanese language of this mod

### ISSUE THREAD

**Issue by Greenjp0025** [hashalite/Freecam#142]
I like this mod very much!
I'm not talking about bugs, etc,
But it didn't support Japanese.
I took the liberty of peeking at the mod's lang file.
I made a Japanese version based on "en_us.json".
You can apply it to this mod.
If you need something else, please let me know in DM:) (Discord)
"ultaraidgreen810"
[Forge 1.18.2ver]

[ja_jp.json](https://github.com/hashalite/Freecam/files/13795562/ja_jp.json)

**Comment by hashalite** [comment]
Hey, thank you for taking the time to translate the mod! Unfortunately the file you provided is for an older version and isn't compatible with the current one. Would you mind reformatting it using [this file](https://github.com/hashalite/Freecam/blob/main/common/src/main/resources/assets/freecam/lang/en_us.json) as reference? 

You may also want to [create a pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) with your changes, so that you can show up as a contributor. If not, posting the file here is fine too.

**Comment by Greenjp0025** [comment]
![image](https://github.com/hashalite/Freecam/assets/139126817/cccd2658-1222-4af3-b72b-f48d8d79c775)
Is it this button?

**Comment by MattSturgeon** [comment]
> Is it this button?

Yes

You can [read more here](https://docs.github.com/ja/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) (in Japanese).

**Comment by Greenjp0025** [comment]
I could not do it.😢
I'll upload the file anyway.
[ja_jp.json](https://github.com/hashalite/Freecam/files/13799199/ja_jp.json)

**Comment by hashalite** [comment]
Added, it will be included in the next release. Thanks again!
