### ISSUE TITLE
Make freecam vanilla movement directly use spectator/creative flying

### ISSUE THREAD

**Issue by Slooshie1** [hashalite/Freecam#17]
I like that vanilla movement is back, but I have one small problem with it: the drifting. I have a mod installed (https://www.curseforge.com/minecraft/mc-mods/nocreativedrift) that disables (or in my case since I changed the settings, reduces) the super slow deceleration when flying in creative or spectator mode, making you stop flying faster. FreeCam still uses default drifting speed and I think it's because it doesn't directly utilize the game's creative/spectator flying, but rather recreates it, and in turn is not affected by the other mod. I could be completely 100% wrong about this claim, but I would really like the no drift mod to work with FreeCam (the amount of time it takes to slow down while flying is freaking annoying lol).

Creative flying with NoCreativeDrift mod:

https://user-images.githubusercontent.com/90230538/161498909-346b693b-d3e3-49ba-b9c8-8c5baa805e9c.mp4

Flying with FreeCam:

https://user-images.githubusercontent.com/90230538/161498979-d4d69fe5-5d09-40a1-9d1d-13940acfba27.mp4

**Comment by hashalite** [comment]
This mod does actually use the built-in creative flight. You are experiencing this because Freecam uses a separate camera entity and NoCreativeDrift only modifies the velocity of MC.player. This is an issue that would have to be solved  on NoCreativeDrift's side (possibly by targeting MC.getCameraEntity() rather than MC.player).
